language: python
cache:
  timeout: 3600
  pip: true
  directories:
    - $HOME/.docker
services:
  - docker
env:
  global:
    - ANSIBLE_FORCE_COLOR=1
    - docker_image=quay.io/loganv/docker-ci
    - docker_command=/lib/systemd/systemd
    - cache_dir=$HOME/.docker
  matrix:
  # LINTERS
  - TOXENV=linters
    CACHE_NAME=linters
  # ANSIBLE 2.2 (OCATA)
  - >
    TOXENV=functional_2.2
    docker_image_tag=ubuntu-xenial
    CACHE_NAME=xenial
  # ANSIBLE 2.3 (PIKE)
  - >
    TOXENV=functional_2.3
    docker_image_tag=ubuntu-xenial
    CACHE_NAME=xenial
  # ANSIBLE stable (OSA MASTER)
  - >
    TOXENV=functional_stable
    docker_image_tag=ubuntu-xenial
    CACHE_NAME=xenial
before_install:
  # Load cached docker images
  - if [[ -d ${cache_dir} ]]; then ls ${cache_dir}/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - if [[ -n ${docker_image_tag} ]]; then docker pull ${docker_image}:${docker_image_tag}; fi
install:
  - pip install tox
script:
  - tox
before_cache:
  # Save tagged docker images
  - >
    mkdir -p ${cache_dir} && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e ${cache_dir}/$1.tar.gz || docker save $0 | gzip -2 > ${cache_dir}/$1.tar.gz'
notifications:
  email: false
