# tasks file for haproxy
---
- name: Check HAProxy version selection
  fail:
    msg: "HAProxy version {{ haproxy_version }} is not supported"
  when: haproxy_version not in haproxy_versions_supported
  tags:
    - configuration
    - haproxy
    - haproxy-check-version-support

- name: Add HAProxy PPA
  apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
  tags:
    - configuration
    - haproxy
    - haproxy-add-repository

- name: Install HAProxy apt packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - configuration
    - haproxy
    - haproxy-install

- name: Create certificate directories on target hosts
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: 0750
  with_items: "{{ haproxy_ssl_map }}"
  tags:
    - configuration
    - haproxy
    - haproxy-configuration
    - haproxy-configuration-ssl

- name: Copy SSL certificate files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0640') }}"
  with_items: "{{ haproxy_ssl_map }}"
  notify:
    - Reload HAProxy
  tags:
    - configuration
    - haproxy
    - haproxy-configuration
    - haproxy-configuration-ssl

- include: configure.yml
  tags:
    - configuration
    - haproxy
    - haproxy-configuration

- name: Set the HAProxy service state {{ haproxy_service_state }}/{{ haproxy_service_enabled }}
  service:
    name: "{{ haproxy_service_name }}"
    state: "{{ haproxy_service_state }}"
    enabled: "{{ haproxy_service_enabled }}"
  tags:
    - configuration
    - haproxy
    - haproxy-start-enable-service
