---
- name: Setup
  hosts: localhost
  vars:
    test_backend_servers:
      - name: test1
        host: 10.0.0.1
      - name: test2
        host: 10.0.0.2
  tasks:
    - name: Add test backend servers to ansible inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.host }}"
        groups:
          - test_backend_servers
      with_items: "{{ test_backend_servers }}"
      changed_when: false

- name: Converge
  hosts: haproxy
  roles:
    - role: "{{ playbook_dir | dirname | dirname | dirname | basename }}"
  post_tasks:
    - name: Install socat for testing
      package:
        name: socat
    - block:
        - name: Check if the haproxy service is running
          command: pgrep haproxy
          changed_when: false
      rescue:
        - name: Capture the HAProxy journalctl logs
          command: journalctl -n 100 -u haproxy
          register: haproxy_journal
        - name: Output the HAProxy journal
          debug:
            msg: "{{ haproxy_journal.stdout }}"

- name: Ensure the test dynamic servers are enabled
  hosts: test_backend_servers
  gather_facts: no
  tasks:
    - name: Ensure the endpoint is enabled
      shell: >
        echo "show stat {{ inventory_hostname }}" |
        socat unix-connect:/var/run/haproxy.stat stdio |
        grep {{ inventory_hostname }} |
        cut -d, -f18
      delegate_to: "{{ item }}"
      with_items: "{{ groups['haproxy'] }}"
      register: haproxy_status
      failed_when: "haproxy_status.stdout != 'no check'"
      changed_when: false
      tags:
        - skip_ansible_lint
